import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "@/components";
import { Navbar } from "@/components/Navbar";
import { Toaster } from "@/components/ui/toaster";
import { QueryClientProvider } from "@/components/QueryClientProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Phone Case",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="flex grainy-light flex-col min-h-[calc(100vh-3.5rem-1px)]">
          <div className="flex-1 flex flex-col h-full">
            <QueryClientProvider>{children}</QueryClientProvider>
            <Footer />
          </div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
